# Generated by Django 3.0.8 on 2021-04-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('profilepic', models.ImageField(upload_to='')),
                ('phoneno', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=30)),
                ('lat', models.CharField(max_length=30)),
                ('long', models.CharField(max_length=30)),
                ('desctext', models.CharField(max_length=30)),
                ('covidnegdate', models.DateField()),
                ('quartype', models.BooleanField()),
                ('govtid', models.ImageField(upload_to='')),
                ('bloodgroup', models.CharField(choices=[('A+ve', 'A+ve'), ('A-ve', 'A-ve'), ('B+ve', 'B+ve'), ('B-ve', 'B-ve'), ('AB+ve', 'AB+ve'), ('AB-ve', 'AB-ve'), ('O+ve', 'O+ve'), ('O-ve', 'O-ve')], max_length=30)),
            ],
        ),
    ]
