# Generated by Django 3.0.8 on 2021-04-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasmasearchapp', '0002_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='covidnegcert',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
