# Generated by Django 3.0.8 on 2021-04-09 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plasmasearchapp', '0005_auto_20210409_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='type',
            field=models.CharField(choices=[('donor', 'donor'), ('recipient', 'recipient')], default='recipient', max_length=30),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='quartype',
            field=models.CharField(choices=[('hospitalized', 'Hospitalized'), ('homequar', 'Home Quarantined')], max_length=30),
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
