# Generated by Django 3.0.8 on 2021-04-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasmasearchapp', '0007_auto_20210409_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestplasma',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
