# Generated by Django 3.0.8 on 2021-04-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasmasearchapp', '0009_auto_20210411_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='lat',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='long',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Userlatlong',
        ),
    ]
