# Generated by Django 3.0.8 on 2021-04-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasmasearchapp', '0010_auto_20210411_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phoneverified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sentotp',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
