# Generated by Django 3.0.8 on 2021-04-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasmasearchapp', '0011_auto_20210416_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='isapproved',
            field=models.BooleanField(default=False),
        ),
    ]
